import { useState } from 'react'
import GlassPanel from '../components/GlassPanel.jsx'
import PageHeader from '../components/PageHeader.jsx'
import { dashboardApi } from '../services/dashboardApi.js'
const INITIAL = { pair: '', timeframe: '', strategy: '', atr_period: '', supertrend_multiplier: '', minimum_rr: '', maximum_spread: '', maximum_slippage: '', maximum_concurrent_positions: '', consecutive_loss_pause: '', cooldown_minutes: '', maximum_holding_minutes: '', session: '', notes: '' }
export default function StrategyMaintenancePage() {
  const [draft, setDraft] = useState(INITIAL); const [result, setResult] = useState(null)
  const update = (key, value, number = false) => setDraft((current) => ({ ...current, [key]: number ? Number(value) : value }))
  const validate = async () => { try { setResult((await dashboardApi.validateStrategyDraft(draft)).data) } catch (error) { setResult({ status: 'INVALID', errors: [error.message] }) } }
  const numeric = [['atr_period','ATR period'],['supertrend_multiplier','Supertrend multiplier'],['minimum_rr','Minimum planned R:R'],['maximum_spread','Maximum spread'],['maximum_slippage','Maximum slippage'],['maximum_concurrent_positions','Maximum concurrent positions'],['consecutive_loss_pause','Consecutive-loss pause threshold'],['cooldown_minutes','Cooldown duration'],['maximum_holding_minutes','Maximum holding time']]
  return <><PageHeader title="Strategy Validation" actions={<span className="readModelBadge">DRAFT ONLY · LIVE BLOCKED</span>} />
    <div className="twoColumn strategyLayout"><GlassPanel family="research"><div className="panelHeading"><div><small>A · STRATEGY CONFIGURATION</small><h2>Research draft</h2></div><span>DRAFT → VALIDATE → EXPORT → REVIEW REQUEST</span></div><form className="draftForm" onSubmit={(e) => e.preventDefault()}>{[['pair','Pair'],['timeframe','Timeframe'],['strategy','Strategy'],['session','Market sessions']].map(([key,label]) => <label key={key}>{label}<input value={draft[key]} onChange={(e) => update(key,e.target.value)} /></label>)}{numeric.map(([key,label]) => <label key={key}>{label}<input type="number" value={draft[key]} onChange={(e) => update(key,e.target.value,true)} /></label>)}<label className="full">Notes<textarea maxLength="2000" value={draft.notes} onChange={(e) => update('notes',e.target.value)} /></label><div className="full actionRow"><button type="button" onClick={validate}>Validate Draft</button><button type="button">Export</button><button type="button">Copy Review Request</button></div></form>{result && <div className={`validationResult ${result.status === 'VALID' ? 'valid' : 'invalid'}`} role="status"><b>{result.status}</b>{result.errors?.map((error) => <span key={error}>{error}</span>)}</div>}<small>Validation performs no persistence, execution, broker contact, backtest, Paper activity, or LIVE activity.</small></GlassPanel>
      <GlassPanel family="neutral"><div className="panelHeading"><div><small>STATUS</small><h2>Validation</h2></div></div><dl className="maintenanceList">{['Strategy state','Evidence','PAPER readiness','LIVE authority','Broker state','Dataset state'].map((label) => <div key={label}><dt>{label}</dt><dd>{label === 'LIVE authority' ? 'BLOCKED' : 'UNAVAILABLE'}</dd></div>)}</dl><div className="calibrationStack"><label>R:R DISPLAY <input type="range" min="2" max="4.5" step=".5" defaultValue="3" /></label><label>PF DISPLAY <input type="range" min="1" max="2" step=".1" defaultValue="1.3" /></label><small>DISPLAY ONLY · NO BROKER AUTHORITY</small></div></GlassPanel></div>
  </>
}
